"""PlatformIO pre-build hook for BoseFix32.

Same contract as in CULFW32 / TCM32 — see /root/.claude/CLAUDE.md global
section "Versioning + lokales Git + Pre-Build-Backup".

For every `pio run` invocation:
  1. If the project is a git repo and the working tree has uncommitted
     changes, snapshot them (`git add -A; git commit`) so we can revert
     to any prior built state. The commit message records the *previous*
     build number — so the commit represents "the state about to be rebuilt".
  2. Increment `build_number.txt`.
  3. Regenerate `src/version.h` with `MAJOR.MINOR.BUILD` and timestamp.

Manual fields:
  - `version.txt`       — `MAJOR.MINOR` (one line, e.g. `0.1`). Bump by hand
    when crossing a meaningful project phase.
  - `build_number.txt`  — auto-incremented; do not edit unless resetting.

This script touches only the project tree. No global git config is modified.
"""

import datetime
import os
import subprocess

Import("env")  # noqa: F821 — injected by PlatformIO

PROJECT_DIR  = env["PROJECT_DIR"]                                       # noqa: F821
VERSION_FILE = os.path.join(PROJECT_DIR, "version.txt")
BUILD_FILE   = os.path.join(PROJECT_DIR, "build_number.txt")
HEADER_FILE  = os.path.join(PROJECT_DIR, "src", "version.h")


def _read_version():
    with open(VERSION_FILE) as f:
        v = f.read().strip()
    parts = v.split(".")
    if len(parts) != 2:
        raise RuntimeError(f"version.txt must contain MAJOR.MINOR — got {v!r}")
    return int(parts[0]), int(parts[1])


def _read_build():
    if not os.path.exists(BUILD_FILE):
        return 0
    with open(BUILD_FILE) as f:
        return int((f.read().strip() or "0"))


def _atomic_write(path, content):
    """Atomic write + fsync — verhindert NULL-bytes-Korruption auf NFS."""
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(content)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)
    # Auch Directory fsync, damit NFS den Rename committet
    try:
        dfd = os.open(os.path.dirname(path) or ".", os.O_RDONLY)
        try: os.fsync(dfd)
        finally: os.close(dfd)
    except OSError:
        pass


def _write_build(n):
    _atomic_write(BUILD_FILE, f"{n}\n")


def _is_git_repo():
    return os.path.isdir(os.path.join(PROJECT_DIR, ".git"))


def _git_run(args, capture=False):
    return subprocess.run(
        ["git"] + args,
        cwd=PROJECT_DIR,
        capture_output=capture,
        text=True,
        check=False,
    )


def _git_has_changes():
    r = _git_run(["status", "--porcelain"], capture=True)
    return bool(r.stdout.strip())


def _git_autocommit(prev_version_str):
    if not _git_has_changes():
        return False
    add = _git_run(["add", "-A"])
    if add.returncode != 0:
        print(f"[version_bump] git add failed (rc={add.returncode}); skip commit")
        return False
    msg = f"build snapshot v{prev_version_str}"
    cm = _git_run(["commit", "-m", msg], capture=True)
    if cm.returncode != 0:
        print(f"[version_bump] git commit skipped: {cm.stdout.strip() or cm.stderr.strip()}")
        return False
    return True


def main():
    major, minor = _read_version()
    prev_build = _read_build()
    new_build  = prev_build + 1
    prev_version = f"{major}.{minor}.{prev_build}"
    new_version  = f"{major}.{minor}.{new_build}"

    # Step 1: snapshot working tree under the *previous* version label.
    if _is_git_repo():
        if _git_autocommit(prev_version):
            print(f"[version_bump] git snapshot committed @ v{prev_version}")
    else:
        print("[version_bump] not a git repo — skipping snapshot")

    # Step 2: bump build counter.
    _write_build(new_build)

    # Step 3: regenerate src/version.h.
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"""// SPDX-License-Identifier: GPL-3.0-or-later
// AUTO-GENERATED by scripts/version_bump.py — do not edit by hand.
// Manual fields are version.txt (MAJOR.MINOR) and build_number.txt.
#ifndef BOSEFIX32_VERSION_H
#define BOSEFIX32_VERSION_H

#define FW_NAME           "BoseFix32"
#define FW_VERSION_MAJOR  {major}
#define FW_VERSION_MINOR  {minor}
#define FW_VERSION_BUILD  {new_build}

#define FW_VERSION_STRING "{new_version}"
#define FW_BUILD_DATE     "{now}"

#endif // BOSEFIX32_VERSION_H
"""
    _atomic_write(HEADER_FILE, header)
    print(f"[version_bump] {new_version} @ {now}")


main()
